config/routes.rb
Cbr::Application.routes.draw do
  resources :clients
  
  

  root :to => "clients#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  client_type :string(255)
#  program     :string(255)
#  location    :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#


class Client < ActiveRecord::Base
end

app/controllers/application_controller.rb
  
 # in your app controller, you'll want to set the layout to nil for XHR (ajax) requests
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout Proc.new { |controller| controller.request.xhr? ? nil : 'application' }
end
  

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  
  def index
    @clients = Client.all    
  end
  
  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new 
  end
  
  def create
    # Instantiate a new object using form parameters
    @client = Client.new(params[:client])
    # Now save the client
    if @client.save
        #if save succeeds
        redirect_to(:action => 'index')
    else
      # if save fails, redisplay the form so user can fix problems
      render('new')
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb


<div class="center">
<%= form_for(:client, :url => {:action => 'create'}) do |f| %>
	
	<ul>
		<li>
			Name:<br/>
			<%= f.text_field(:name) %>
		</li>
		<li>
			Client Type:<br/>
			<%= f.text_field(:client_type) %>
		</li>
		<li>
			Account/Program:<br/>
			<%= f.text_field(:program) %>
		</li>
		<li>
			Geo Location:<br/>
			<%= f.text_field(:location) %>
		</li>
	</ul>

	<div>
		<ul>		
			<li class="left"><%= submit_tag "Create Client", :class => '' %> </li>
			<li><%= button_to "Cancel", '#', :class => 'close'  %>	</li>
		</ul>
	</div>
	
<% end %>

</div>


app/views/clients/index.html.erb
<script type="text/javascript">
	$(document).ready(function() {
    $('#example').dataTable();
} );
</script>

<h2>Clients</h2>

<p>
<%= link_to "New Client", new_client_path, :remote => true, :class => "new_button round" %>
</p>

			
<div>
	<table cellpadding="0" cellspacing="0" border="0" class="display" id="example">
		<thead>
			<tr>			
				<th>Client Name</th>
				<th>Client Type</th>
				<th>Account/Program</th>			
				<th>Geo Location</th>
			</tr>
		</thead>
		<tbody>
			<% @clients.each do |client| %>
				<tr>
					<td><%= client.name %></td>
					<td><%= client.client_type %></td>
					<td><%= client.program %></td>
					<td><%= client.location %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	
			
			
			<div id="modal-container">
				<div id="modal" class="round">
							  		
				</div>
			</div>
			
			
	
</div>

app/views/clients/new.html.erb
<h1>Create New Client</h1>

<%= render 'form' %>

app/views/clients/show.html.erb
<div>
	<ul>
		<li><strong>Client Name:</strong>  <%= @client.name %></li>
		<li><strong>Client Type:</strong>  <%= @client.client_type %></li>
		<li><strong>Account/Program:</strong>   <%= @client.program %></li>
		<li><strong>Geo Location:</strong>  <%= @client.location %></li>
		
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cbr</title>
   <%= csrf_meta_tag %>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
    <%= stylesheet_link_tag 'demo_table',  :media => 'screen' %>
    <%= stylesheet_link_tag 'demo_table_jui',  :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>  	
  	
  	<%= javascript_include_tag :defaults %>   	  	
  	<%= javascript_include_tag 'jquery.dataTables.js' %>
  	
</head>
<body>
	<div class="container">
		<nav class="round">
	      <ul>
	        <li><%= link_to "Client List", root_path, :class => 'nav_button' %></li>
	        <li><%= link_to "Jobs List", '#', :class => 'nav_button' %></li>
	        <li><%= link_to "Master Contacts", '#', :class => 'nav_button' %></li>
	        <li><%= link_to "Quick Reference Guides", '#', :class => 'nav_button' %></li>
	        <li><%= link_to "Bulletins", '#', :class => 'nav_button' %></li>
	      </ul>
	    </nav>
		
			
		
		<section class="round" style="clear: both;">			
			
			
			<%= yield %>
		
			

		</section>
	</div>

</body>
</html>